# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HThSe6r9HY5KnVZBT3WTEiwOwvVg8iYq
"""

import numpy as np

def euclidean_distance(row1, row2):
    squaredDifference = [(row1[i] - row2[i]) ** 2 for i in range(len(row1))]
    distance = sum(squaredDifference) ** 0.5
    return distance

def knn(X_train, y_train, X_test, kvalue):
    y_pred = []

    for test_point in X_test:
        distance = [euclidean_distance(test_point, train_point) for train_point in X_train]
        nearestIndice = np.argsort(distance)[:kvalue]
        nearestLabel = [y_train[i] for i in nearestIndice]
        predictedLabel = max(set(nearestLabel), key=nearestLabel.count)
        y_pred.append(predictedLabel)

    return np.array(y_pred)

def compute_accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

X_train, y_train = train_feats, train_labels
X_val, y_val = val_feats, val_labels

k_value = 5

y_train_pred = knn(X_train, y_train, X_train, k_value)

train_accuracy = compute_accuracy(y_train, y_train_pred)
print(f"Training accuracy): {train_accuracy * 100:.2f}%")

y_val_pred = knn(X_train, y_train, X_val, k_value)

val_accuracy = compute_accuracy(y_val, y_val_pred)
print(f"Validation accuracy): {val_accuracy * 100:.2f}%")