# -*- coding: utf-8 -*-
"""Spectral Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XyGP7-HPVNSJkwTh9awDp2kcNG5uvV-t
"""

from google.colab import drive
drive.mount('/content/drive')
data_file = '/content/drive/MyDrive/data/songs.csv'

import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform
from scipy.linalg import eigh
from scipy.stats import ttest_ind

#load data
data = pd.read_csv(data_file)
X = data.values

#calculate euclidean distance
n = X.shape[0]
distance = np.zeros((n, n))
for i in range(n):
    for j in range(i+1, n):
        distance[i, j] = np.sqrt(np.sum((X[i] - X[j])**2))
        distance[j, i] = distance[i, j]

#calculate matrices
A = (distance < 1).astype(int)
D = np.diag(A.sum(axis=1))
L = D - A

#test
#np.set_printoptions(threshold=np.inf, linewidth=np.inf)
#print("adjacency matrix subset test")
#print(A[:100, :100])

#normalize laplacian
D_inv_sqrt = np.linalg.inv(np.sqrt(D))
L_norm = D_inv_sqrt @ L @ D_inv_sqrt

#eigendecomposition
evals, evecs = eigh(L_norm)

#select 2nd smallest eigevector and normalize
v2 = evecs[:,1]
x = D_inv_sqrt @ v2

#test
#print("\neigenvalues:")
#print(evals[:5])

#assign labels
labels = np.where(x >= 0, 1, 0)

#test
#sanity_check_indices = [5, 6, 7]
#sanity_check_labels = labels[sanity_check_indices]
#print("Labels for songs 6, 7, 8:", sanity_check_labels)
#print(labels[:5])

#print clustering results and artist_familiarity score for the first 5 users
print("clustering results for first 5 songs:")
for i in range(5):
    song = data.iloc[i, 0]
    label = labels[i]
    artist_familiarity = data.iloc[i, data.columns.get_loc('artist_familiarity')]
    print(f"song {i + 1} ----> cluster {label}, artist familiarity: {artist_familiarity}")

#cluster features
cluster_means = data.groupby(labels).mean()
mean_diffs = np.abs(cluster_means.diff()).iloc[1]

print("\nTop 3 features:")
print(mean_diffs.nlargest(3))

print("\nT-test:")
for feat in mean_diffs.nlargest(3).index:
    x0 = data.loc[labels == 0, feat]
    x1 = data.loc[labels == 1, feat]
    t, p = ttest_ind(x0, x1, equal_var=True)
    print(f"{feat}: p-value = {p:.3g}")